//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AwardFestival
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AwardFestival()
        {
            this.MovieFestivalAwards = new HashSet<MovieFestivalAward>();
        }
    
        public int Award_Id { get; set; }
        public int Festival_Id { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Award Award { get; set; }
        public virtual Festival Festival { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MovieFestivalAward> MovieFestivalAwards { get; set; }
    }
}
