//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieFestivalAward
    {
        public int AwardFestival_Award_Id { get; set; }
        public int AwardFestival_Festival_Id { get; set; }
        public int MovieFestival_Movie_Id { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual AwardFestival AwardFestival { get; set; }
    }
}
