//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int Critic_Id { get; set; }
        public Nullable<int> Rate { get; set; }
        public int Movie_Id { get; set; }
        public bool Deleted { get; set; }
        public Nullable<bool> Approved { get; set; }
        public Nullable<System.DateTime> ApprovalDateTime { get; set; }
    
        public virtual Critic Critic { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
