//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowsMovie
    {
        public int Cinema_Id { get; set; }
        public int Movie_Id { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public Nullable<bool> Deleted { get; set; }
    
        public virtual Cinema Cinema { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
